version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 7
    commit-message:
      prefix: "MAINT"
    labels:
      - "03 - Maintenance"
    ignore:
      - dependency-name: "bus1/cabuild"
updates:
  - package-ecosystem: pip
    directory: /requirements
    schedule:
      interval: daily
    cooldown:
      default-days: 7
    commit-message:
      prefix: "MAINT"
    labels:
      - "03 - Maintenance"
    ignore:
      - dependency-name: "scipy-openblas32"
      - dependency-name: "scipy-openblas64"
      - dependency-name: "jupyterlite-pyodide-kernel"
      - dependency-name: "sphinx"
