# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
matrix:
  include:
    - python: 3.3
      env: USE_CHROOT=1 ARCH=i386 DIST=trusty PYTHON=3.4
    - python: 3.2
      env: USE_DEBUG=1
    - python: 2.7
      env: NPY_SEPARATE_COMPILATION=0 PYTHON_OO=1
    - python: 3.4
      env: NPY_RELAXED_STRIDES_CHECKING=0
# disable bento test until waf issue is resolved.
#    - python: 2.7
#      env: USE_BENTO=1
    - python: 2.7
      env: USE_WHEEL=1
before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - mkdir builds
  - pushd builds
  - pip install nose
  # pip install coverage
  - python -V
  - pip install --upgrade pip setuptools
  # Speed up install by not compiling Cython
  - pip install --install-option="--no-cython-compile" Cython
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev gfortran
  - popd

script:
  - ./tools/travis-test.sh
