# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
group: travis_latest
os: linux
dist: focal

# Travis allows these packages, additions can be requested
#   https://github.com/travis-ci/apt-package-safelist
addons:
  apt:
    packages: &common_packages
      - gfortran
      - libgfortran5
      - libatlas-base-dev
      # Speedup builds, particularly when USE_CHROOT=1
      - eatmydata

# Disable clone depth
git:
  depth: false

cache:
  directories:
    - $HOME/.cache/pip

jobs:
  include:
    - python: "3.8"
      os: linux
      arch: ppc64le
      env:
       # use OpenBLAS build, not system ATLAS
       - DOWNLOAD_OPENBLAS=1
       - NPY_USE_BLAS_ILP64=1
       - ATLAS=None

    - python: "3.8"
      os: linux
      arch: s390x
      env:
       # use OpenBLAS build, not system ATLAS
       - DOWNLOAD_OPENBLAS=1
       - NPY_USE_BLAS_ILP64=1
       - ATLAS=None

    # Wheel builders
    - python: "3.8"
      os: linux
      arch: arm64
      virt: vm
      env:
        - CIBW_BUILD: cp38-manylinux_aarch64
      install: python3 -m pip install cibuildwheel==2.6.0
      script: |
        cibuildwheel --output-dir wheelhouse
        source ./tools/wheels/upload_wheels.sh
        set_travis_vars
        set_upload_vars
        upload_wheels # Will be skipped if not a push/tag/scheduled build
    - python: "3.9"
      os: linux
      arch: arm64
      virt: vm
      env:
        - CIBW_BUILD: cp39-manylinux_aarch64
      install: python3 -m pip install cibuildwheel==2.6.0
      script: |
        cibuildwheel --output-dir wheelhouse
        source ./tools/wheels/upload_wheels.sh
        set_travis_vars
        set_upload_vars
        upload_wheels # Will be skipped if not a push/tag/scheduled build
    - python: "3.10"
      os: linux
      arch: arm64
      virt: vm
      env:
        - CIBW_BUILD: cp310-manylinux_aarch64
      install: python3 -m pip install cibuildwheel==2.6.0
      script: |
        cibuildwheel --output-dir wheelhouse
        source ./tools/wheels/upload_wheels.sh
        set_travis_vars
        set_upload_vars
        upload_wheels # Will be skipped if not a push/tag/scheduled build
before_install:
  - ./tools/travis-before-install.sh

script:
  - ./tools/travis-test.sh
