# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
group: travis_latest
os: linux
dist: bionic

# Travis allows these packages, additions can be requested
#   https://github.com/travis-ci/apt-package-safelist
addons:
  apt:
    packages: &common_packages
      - gfortran
      - libgfortran5
      - libatlas-base-dev
      # Speedup builds, particularly when USE_CHROOT=1
      - eatmydata

# Disable clone depth
git:
  depth: false

cache:
  directories:
    - $HOME/.cache/pip

jobs:
  include:
    - python: 3.7
      os: linux
      arch: ppc64le
      env:
       # use OpenBLAS build, not system ATLAS
       - DOWNLOAD_OPENBLAS=1
       - ATLAS=None

    - python: 3.7
      os: linux
      arch: s390x
      env:
       # use OpenBLAS build, not system ATLAS
       - DOWNLOAD_OPENBLAS=1
       - NPY_USE_BLAS_ILP64=1
       - ATLAS=None

    - python: 3.7
      os: linux
      arch: arm64
      env:
       # use OpenBLAS build, not system ATLAS
       - DOWNLOAD_OPENBLAS=1
       - ATLAS=None


before_install:
  - ./tools/travis-before-install.sh

script:
  - ./tools/travis-test.sh
