# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
group: travis_latest
os: linux
dist: focal

# Travis allows these packages, additions can be requested
#   https://github.com/travis-ci/apt-package-safelist
addons:
  apt:
    packages: &common_packages
      - gfortran
      - libgfortran5
      - libatlas-base-dev
      # Speedup builds, particularly when USE_CHROOT=1
      - eatmydata

# Disable clone depth
git:
  depth: false

cache:
  directories:
    - $HOME/.cache/pip

jobs:
  include:
    - python: "3.8"
      os: linux
      arch: ppc64le
      env:
       # use OpenBLAS build, not system ATLAS
       - DOWNLOAD_OPENBLAS=1
       - NPY_USE_BLAS_ILP64=1
       - ATLAS=None
       # VSX4 still not supported by ubuntu/gcc-11
       - EXPECT_CPU_FEATURES="VSX VSX2 VSX3"

    - python: "3.8"
      os: linux
      arch: s390x
      # fixes VX assembler ambiguous errors
      # due to compiler incompatibility
      install: sudo apt update && sudo apt -y --only-upgrade install binutils
      env:
       # use OpenBLAS build, not system ATLAS
       - DOWNLOAD_OPENBLAS=1
       - NPY_USE_BLAS_ILP64=1
       - ATLAS=None
       - EXPECT_CPU_FEATURES="VX VXE VXE2"

    # Wheel builders
    # Note that Ubuntu focal comes with Python 3.8 and CIBW_BUILD determines
    # the Python used to build the wheels.
    - python: "3.8"
      os: linux
      arch: arm64
      virt: vm
      env:
        - CIBW_BUILD: cp38-manylinux_aarch64
        - EXPECT_CPU_FEATURES: "NEON NEON_FP16 NEON_VFPV4 ASIMD ASIMDHP ASIMDDP ASIMDFHM"
      install: python3 -m pip install cibuildwheel==2.11.2
      script: |
        cibuildwheel --output-dir wheelhouse
        source ./tools/wheels/upload_wheels.sh
        set_travis_vars
        set_upload_vars
        upload_wheels # Will be skipped if not a push/tag/scheduled build
    - python: "3.8"
      os: linux
      arch: arm64
      virt: vm
      env:
        - CIBW_BUILD: cp39-manylinux_aarch64
      install: python3 -m pip install cibuildwheel==2.11.2
      script: |
        cibuildwheel --output-dir wheelhouse
        source ./tools/wheels/upload_wheels.sh
        set_travis_vars
        set_upload_vars
        upload_wheels # Will be skipped if not a push/tag/scheduled build
    - python: "3.8"
      os: linux
      arch: arm64
      virt: vm
      env:
        - CIBW_BUILD: cp310-manylinux_aarch64
      install: python3 -m pip install cibuildwheel==2.11.2
      script: |
        cibuildwheel --output-dir wheelhouse
        source ./tools/wheels/upload_wheels.sh
        set_travis_vars
        set_upload_vars
        upload_wheels # Will be skipped if not a push/tag/scheduled build
    - python: "3.8"
      os: linux
      arch: arm64
      virt: vm
      env:
        - CIBW_BUILD: cp311-manylinux_aarch64
      install: python3 -m pip install cibuildwheel==2.11.2
      script: |
        cibuildwheel --output-dir wheelhouse
        source ./tools/wheels/upload_wheels.sh
        set_travis_vars
        set_upload_vars
        upload_wheels # Will be skipped if not a push/tag/scheduled build
before_install:
  - ./tools/travis-before-install.sh

script:
  - ./tools/travis-test.sh
