# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
group: travis_latest
os: linux
dist: bionic

# Travis allows these packages, additions can be requested
#   https://github.com/travis-ci/apt-package-safelist
addons:
  apt:
    packages: &common_packages
      - gfortran
      - libgfortran5
      - libatlas-base-dev
      # Speedup builds, particularly when USE_CHROOT=1
      - eatmydata

cache:
  directories:
    - $HOME/.cache/pip

stages:
    # Do the style check and a single test job, don't proceed if it fails
    - name: Initial tests
    # Do the rest of the tests
    - name: Comprehensive tests

jobs:
  include:
    # Do all python versions without environment variables set
    - stage: Initial tests
      python: 3.8

    - stage: Comprehensive tests
      python: 3.7
      os: linux
      arch: ppc64le
      env:
       # use OpenBLAS build, not system ATLAS
       - DOWNLOAD_OPENBLAS=1
       - ATLAS=None

    - python: 3.7
      os: linux
      arch: s390x
      env:
       # use OpenBLAS build, not system ATLAS
       - DOWNLOAD_OPENBLAS=1
       - NPY_USE_BLAS_ILP64=1
       - ATLAS=None

    - python: 3.7
      os: linux
      arch: arm64
      env:
       # use OpenBLAS build, not system ATLAS
       - DOWNLOAD_OPENBLAS=1
       - ATLAS=None



    - python: 3.6
    - python: 3.7
    - python: 3.9-dev

    - python: 3.8
      dist: focal
      env: USE_DEBUG=1
      addons:
        apt:
          packages:
            - *common_packages
            - cython3-dbg
            - python3-dbg
            - python3-dev
            - python3-setuptools

    - python: 3.7
      env: USE_WHEEL=1 RUN_FULL_TESTS=1 RUN_COVERAGE=1 INSTALL_PICKLE5=1

    - python: 3.7
      env: USE_SDIST=1

    - python: 3.7
      env:
       - PYTHONOPTIMIZE=2
       - BLAS=None
       - LAPACK=None
       - ATLAS=None
       - NPY_BLAS_ORDER=mkl,blis,openblas,atlas,blas
       - NPY_LAPACK_ORDER=MKL,OPENBLAS,ATLAS,LAPACK
       - USE_ASV=1

    - python: 3.7
      env:
        - NPY_RELAXED_STRIDES_CHECKING=0
        # use custom symbol-suffixed openblas build, not system ATLAS
        - DOWNLOAD_OPENBLAS=1
        - CHECK_BLAS=1
        - NPY_USE_BLAS_ILP64=1
      addons:
        apt:
          packages:
            - gfortran
            - eatmydata
            - libgfortran5
            - libgfortran3

    - python: 3.7
      env: USE_WHEEL=1 NPY_RELAXED_STRIDES_DEBUG=1

    - python: 3.7
      env: NUMPY_EXPERIMENTAL_ARRAY_FUNCTION=0

    - python: 3.7
      env:
       - BLAS=None
       - LAPACK=None
       - ATLAS=None



before_install:
  - ./tools/travis-before-install.sh

script:
  - ./tools/travis-test.sh
