# To use:
#
#   $ conda env create -f environment.yml  # `mamba` works too for this command
#   $ conda activate numpy-dev
#
name: numpy-dev
channels:
  - conda-forge
dependencies:
  - python
  - cython
  - compilers
  - openblas
  - nomkl
  - setuptools=59.2.0
  # For testing
  - pytest
  - pytest-cov
  - pytest-xdist
  - hypothesis
  # For type annotations
  - mypy=0.930
  # For building docs
  - sphinx=4.1.1
  - numpydoc=1.1.0
  - ipython
  - scipy
  - pandas
  - matplotlib
  - pydata-sphinx-theme
  - breathe
  # For linting
  - pycodestyle=2.7.0
  - gitpython
  # Used in some tests
  - cffi
  - pytz
