[workspace]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["osx-arm64", "linux-64"]
preview = ["pixi-build"]

[package.build]
source.path = "../.."

[package.build.backend]
name = "pixi-build-python"
version = "*"

[package.build.config]
extra-input-globs = ["**/*.c.src"]
compilers = ["c", "cxx"]
extra-args = ["-Csetup-args=-Dbuildtype=debug"]

[package.host-dependencies]
# FIXME https://github.com/numpy/numpy/issues/30561
# python = "*" prevents downstream from building cpython from sources.
# Workaround: fork numpy, then uncomment one of the following and
# comment  out the other.

# Use latest cpython release from conda-forge
# python-freethreading = "*"

# Use cpython git tip
python.git = "https://github.com/crusaderky/cpython"
python.subdirectory = "Tools/pixi-packages/freethreading"
python.rev = "tsan"

meson-python = "*"
cython = "*"
uv = "*" # used to invoke the wheel build
