name: Build_Test

on: [push, pull_request]

defaults:
  run:
    shell: bash

env: 
  DOWNLOAD_OPENBLAS: 1
  PYTHON_VERSION: 3.7

jobs:
  smoke_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - uses: ./.github/actions
 
  basic:
    needs: smoke_test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - uses: ./.github/actions

  debug:
    needs: smoke_test
    runs-on: ubuntu-latest
    env:
      USE_DEBUG: 1
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - uses: ./.github/actions

  blas64:
    needs: smoke_test
    runs-on: ubuntu-latest
    env:
      NPY_USE_BLAS_ILP64: 1
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - uses: ./.github/actions

  full:
    needs: smoke_test
    runs-on: ubuntu-latest
    env:
      USE_WHEEL: 1
      RUN_FULL_TESTS: 1
      RUN_COVERAGE: 1
      INSTALL_PICKLE5: 1
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - uses: ./.github/actions

  benchmark:
    needs: smoke_test
    runs-on: ubuntu-latest
    env:
      PYTHONOPTIMIZE: 2
      BLAS: None
      LAPACK: None
      ATLAS: None
      NPY_BLAS_ORDER: mkl,blis,openblas,atlas,blas
      NPY_LAPACK_ORDER: MKL,OPENBLAS,ATLAS,LAPACK
      USE_ASV: 1
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - uses: ./.github/actions

  no_relaxed_strides:
    needs: smoke_test
    runs-on: ubuntu-latest
    env:
      NPY_RELAXED_STRIDES_CHECKING: 0
      CHECK_BLAS: 1
      NPY_USE_BLAS_ILP64: 1
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - uses: ./.github/actions

  use_wheel:
    needs: smoke_test
    runs-on: ubuntu-latest
    env:
      USE_WHEEL: 1
      NPY_RELAXED_STRIDES_DEBUG: 1
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - uses: ./.github/actions

  no_array_func:
    needs: smoke_test
    runs-on: ubuntu-latest
    env:
      NUMPY_EXPERIMENTAL_ARRAY_FUNCTION: 0
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - uses: ./.github/actions

  no_openblas:
    needs: smoke_test
    runs-on: ubuntu-latest
    env:
      BLAS: None
      LAPACK: None
      ATLAS: None
      DOWNLOAD_OPENBLAS: ''
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - uses: ./.github/actions

  pypy37:
    needs: smoke_test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0
    - name: get_pypy
      run: |
        wget -q https://downloads.python.org/pypy/pypy3.6-v7.3.2-linux64.tar.bz2 -O pypy.tar.bz2
        mkdir -p pypy3
        (cd pypy3; tar --strip-components=1 -xf ../pypy.tar.bz2)
        pypy3/bin/pypy3 -mensurepip
        pypy3/bin/pypy3 -m pip install --upgrade pip wheel
        if [ ! -e pypy3/bin/python ]
        then
            pushd pypy3/bin
            ln -s pypy3 python
            popd
        fi
        echo $PWD/pypy3/bin >> $GITHUB_PATH
 
    - uses: ./.github/actions

       
