# To enable this workflow on a fork, comment out:
#
# if: github.repository == 'numpy/numpy'

name: CircleCI artifact redirector

on: [status]

permissions: read-all

jobs:
  circleci_artifacts_redirector_job:
    runs-on: ubuntu-latest
    if: "github.repository == 'numpy/numpy' && !contains(github.event.head_commit.message, '[circle skip]') && !contains(github.event.head_commit.message, '[skip circle]')  && github.event.context == 'ci/circleci: build'"
    name: Run CircleCI artifacts redirector
    # if: github.repository == 'numpy/numpy'
    permissions:
      statuses: write
    steps:
      - name: GitHub Action step
        uses: larsoner/circleci-artifacts-redirector-action@24d48fa16ba1f5e23907ebcb74150363d37499d3 # master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          artifact-path: 0/doc/build/html/index.html
          circleci-jobs: build
