# To enable this workflow on a fork, comment out:
#
# if: github.repository == 'numpy/numpy'
name: Test Emscripten/Pyodide build

on:
  pull_request:
    branches:
      - main
      - maintenance/**

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build-wasm-emscripten:
    runs-on: ubuntu-22.04
    if: "github.repository == 'numpy/numpy'"
    env:
      PYODIDE_VERSION: 0.23.1
      # PYTHON_VERSION and EMSCRIPTEN_VERSION are determined by PYODIDE_VERSION.
      # The appropriate versions can be found in the Pyodide repodata.json
      # "info" field, or in Makefile.envs:
      # https://github.com/pyodide/pyodide/blob/main/Makefile.envs#L2
      PYTHON_VERSION: 3.11.2
      EMSCRIPTEN_VERSION: 3.1.32
      NODE_VERSION: 18
    steps:
      - name: Checkout numpy
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          submodules: true
          # versioneer.py requires the latest tag to be reachable. Here we
          # fetch the complete history to get access to the tags.
          # A shallow clone can work when the following issue is resolved:
          # https://github.com/actions/checkout/issues/338
          fetch-depth: 0

      - name: set up python
        id: setup-python
        uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v4.7.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - uses: mymindstorm/setup-emsdk@ab889da2abbcbb280f91ec4c215d3bb4f3a8f775 # v12
        with:
          version: ${{ env.EMSCRIPTEN_VERSION }}
          actions-cache-folder: emsdk-cache

      - name: Install pyodide-build
        run: pip install "pydantic<2" build pyodide-build==$PYODIDE_VERSION

      - name: Build
        run: |
          # Note that we need to cross-compile here. Using `pyodide build`
          # fails on not having a cross file. The `source() function in
          # `pyodide_build/cli/build.py` needs a --backend-flags parameter so
          # that we can pass config-settings arguments to the backend.
          # We'll then run into static assert issues in `pyconfig.h` due to:
          # https://github.com/pyodide/pyodide/pull/2494#issuecomment-1118500743
          # See also https://github.com/pyodide/pyodide/pull/2238 and the patches
          # to _numpyconfig.h in https://github.com/pyodide/pyodide/tree/main/packages/numpy
          #
          # tl;dr this needs some work, and it seems like cross-compilation is
          # hard because Pyodide doesn't ship its own Python interpreter that
          # we can actually target during a direct cross build.
          python -m build --wheel -Csetup-args=--cross-file=$PWD/tools/ci/emscripten.meson.cross -Csetup-args=-Dallow-noblas=true

      - name: set up node
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Set up Pyodide virtual environment
        run: |
          pyodide venv .venv-pyodide
          source .venv-pyodide/bin/activate
          pip install dist/*.whl
          python -c "import sys; print(sys.platform)"
          pip install -r test_requirements.txt
      - name: Test
        run: |
          source .venv-pyodide/bin/activate
          cd ..
          pytest --pyargs numpy -m "not slow"
