name: iOS tests

on:
  pull_request:
    branches:
      - main
      - maintenance/**
    paths-ignore:
      - '**.pyi'
      - '**.md'
      - '**.rst'

env:
  FORCE_COLOR: 3

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-ios:
    permissions:
      contents: read  # to fetch code (actions/checkout)
    name: Test (${{ matrix.runs-on }} ${{ matrix.accelerated && 'accelerated' || 'non-accelerated' }})
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on: ["macos-14", "macos-15-intel"]
        accelerated: [true, false]

    # To enable this workflow on a fork, comment out:
    if: github.repository == 'numpy/numpy'
    steps:
      - name: Checkout NumPy
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
        with:
          submodules: recursive
          fetch-tags: true
          persist-credentials: false

      - name: Setup iOS
        run: |
          if [[ ${{ matrix.accelerated }} ]]; then
            # Accelerate with ILP64 requires iOS 16.4 or higher
            CIBW="IPHONEOS_DEPLOYMENT_TARGET=17.0 INSTALL_OPENBLAS=false RUNNER_OS=iOS"
          else
            CIBW="INSTALL_OPENBLAS=false RUNNER_OS=iOS"
          fi
          echo "CIBW_ENVIRONMENT_IOS=$CIBW" >> "$GITHUB_ENV"

      - name: Build wheels
        uses: pypa/cibuildwheel@9c00cb4f6b517705a3794b22395aedc36257242c  # v3.2.1
        env:
          CIBW_PLATFORM: ios
