name: Test Meson build (Linux)

on:
  push:
    branches:
      - meson
  pull_request:
    branches:
      - meson

defaults:
  run:
    shell: bash

env:
  PYTHON_VERSION: 3.11

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  meson_devpy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Install dependencies
      run: |
        pip install -r build_requirements.txt
        sudo apt-get install -y libopenblas-serial-dev
    - name: Build
      run:
        ./dev.py build -- --werror
    - name: Check build-internal dependencies
      run:
        ninja -C build -t missingdeps
    - name: Check installed test and stub files
      run:
        python tools/check_installed_files.py build-install/usr/lib/python3.11/site-packages/numpy/
    - name: Test
      run: |
        pip install pytest hypothesis typing_extensions
        ./dev.py test
