name: Native ppc64le and s390x Linux Tests

on:
  pull_request:
    branches:
      - main
      - maintenance/**
    paths-ignore:
      - '**.pyi'
      - '**.md'
      - '**.rst'
      - 'tools/stubtest/**'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  native_ppc64le_and_s390x:
    # These jobs runs only in the main NumPy repository.
    # It requires a native ppc64le and s390x GHA runners, which are not available on forks.
    # For more details, see: https://github.com/numpy/numpy/issues/29125
    if: github.repository == 'numpy/numpy'
    runs-on: ${{ matrix.config.runner }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - name: "GCC (ppc64le)"
            args: "-Dallow-noblas=false"
            runner: ubuntu-24.04-ppc64le-p10
            compiler: "gcc"
          - name: "clang (ppc64le)"
            args: "-Dallow-noblas=false"
            runner: ubuntu-24.04-ppc64le-p10
            compiler: "clang"
          - name: "GCC (s390x)"
            args: "-Dallow-noblas=false"
            runner: ubuntu-24.04-s390x
            compiler: "gcc"
          - name: "GCC with zvector (s390x)"
            args: "-Dallow-noblas=false -Dcpu-baseline=vx"
            runner: ubuntu-24.04-s390x
            compiler: "gcc"

    name: "${{ matrix.config.name }}"
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        submodules: recursive
        fetch-tags: true

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3.12 python3-pip python3-dev ninja-build gfortran \
                            build-essential libopenblas-dev liblapack-dev pkg-config
        pip install --upgrade pip
        pip install -r requirements/build_requirements.txt -r requirements/test_requirements.txt
        echo "/home/runner/.local/bin" >> $GITHUB_PATH

    - name: Install clang
      if: matrix.config.compiler == 'clang'
      run: |
        sudo apt install -y clang-20
        echo CC=clang-20 >> $GITHUB_ENV
        echo CXX=clang++-20 >> $GITHUB_ENV

    - name: Meson Build
      run: |
        spin build -- ${{ matrix.config.args }}

    - name: Meson Log
      if: always()
      run: cat build/meson-logs/meson-log.txt

    - name: Run Tests
      run: |
        spin test -- --timeout=60 --durations=10
