name: Native ppc64le Linux Test

on:
  pull_request:
    branches:
      - main
      - maintenance/**
    paths-ignore:
      - '**.pyi'
      - '**.md'
      - '**.rst'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  native_ppc64le:
    # This job runs only in the main NumPy repository.
    # It requires a native ppc64le GHA runner, which is not available on forks.
    # For more details, see: https://github.com/numpy/numpy/issues/29125
    if: github.repository == 'numpy/numpy'
    runs-on: ubuntu-24.04-ppc64le-p10
    name: "Native PPC64LE"
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        submodules: recursive
        fetch-tags: true
        persist-credentials: false

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip python3-dev ninja-build gfortran \
                            build-essential libopenblas-dev liblapack-dev pkg-config
        pip install --upgrade pip
        pip install -r requirements/build_requirements.txt -r requirements/test_requirements.txt
        echo "/home/runner/.local/bin" >> $GITHUB_PATH

    - name: Meson Build
      run: |
        spin build -- -Dallow-noblas=false

    - name: Meson Log
      if: always()
      run: cat build/meson-logs/meson-log.txt

    - name: Run Tests
      run: |
        spin test -- --timeout=60 --durations=10
